### PR TITLE
Component types export

### LINKED ISSUE #955: [BUG] opensearchtypes export and api/types subpath have been removed from v3, cannot import API inner types anymore ?
### What is the bug?

In v2 it was possible to access API inner types (QueryDslQueryContainer as an example) directly, either using opensearchtypes export from main index, or since #674 using the api/types subpath

eg with opensearchtypes 
```
import type { opensearchtypes } from '@opensearch-project/opensearch';

const buildQuery = (): opensearchtypes.QueryDslQueryContainer => {
  return {
    // TODO
  };
};
```

and with api/types subpath
```
import type { QueryDslQueryContainer } from '@opensearch-project/opensearch/api/types';

const buildQuery = (): QueryDslQueryContainer => {
  return {
    // TODO
  };
};
```

### How can one reproduce the bug?
After upgrade to v3, opensearchtypes export is no more present and api/types expotred subpath has been removed from package.json
(BTW, I did see mention of these breaking changes in the release note, so i may suspect theses changes are not intentional ?)

The corresponding type in v3 is QueryContainer in api/_types/_common.query_dsl.d.ts but it's not exported by the module

I have tried
```
import type { QueryContainer } from '@opensearch-project/opensearch/api/_types/_common.query_dsl';

const buildQuery = (): QueryContainer => {
  return {
    // TODO
  };
};
```

it's recognized in the IDE, but, as expected, rejected by typescript

```
test.ts:1:37 - error TS2307: Cannot find module '@opensearch-project/opensearch/api/_types/_common.query_dsl' or its corresponding type declarations.

1 import type { QueryContainer } from '@opensearch-project/opensearch/api/_types/_common.query_dsl';
```

I may have miss something, but so far I didn't found a way to import this type.

### What is the expected behavior?
Having a simple way to import API inner types directly

### What is your host/environment?
Non relevant

### Do you have any screenshots?
Non relevant

### Do you have any additional context?
No

### PR DESCRIPTION
**Pull request by xfournet**
### Description

Export the TS type in api/_types to Types

### Issues Resolved

Closes #955

### Check List

- [ ] New functionality includes testing  -> I didn't see tests for generator
- [X] All tests pass
- [X] Linter check was successfull - `yarn run lint` doesn't show any errors
- [X] Commits are signed per the DCO using --signoff
- [X] Changelog was updated.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by xfournet** [comment]
> Looks great! There's a [type error ](https://github.com/opensearch-project/opensearch-js/actions/runs/12689156789/job/35383092271?pr=957) in CI tho. You will have to run the generator and commit the changes from the generator as well.

> I'm manually [triggering the api_gen workflow](https://github.com/opensearch-project/opensearch-js/pull/958) so that your PR will only contain the changes from the new type module. Don't forget to rebase.

The type error is because i didn't commit the ouput of the generator so far :) you should trigger the api_gen workflow first ?

**Comment by xfournet** [comment]
I get a lot of unrelated diff (same result without my change).
Do I need to use a precise version of the opensearch-openapi.yaml or use the latest anyway ? in the later case i will separate the 'update to latest spec' commit from the others

image

**Comment by nhtruong** [comment]
The spec repo gets updated very frequently. So every time you download the latest spec, there will be other API changes to the client. It's okay to have some in your PR. We need to see what the new generated `Types` module will look like and if it causes any type error for this PR.

**Comment by xfournet** [comment]
@nhtruong my bad i didn't understand you committed the update on the main branch. Since the spec have change again :( wouldn't be better to commit the downloaded opensearch-openapi.yaml (or commit a 'frozen' link if possible ?) so it's clear which version has been used for the generation ?

**Comment by nhtruong** [comment]
> wouldn't be better to commit the downloaded opensearch-openapi.yaml (or commit a 'frozen' link if possible ?) so it's clear which version has been used for the generation ?

That's a great idea. @dblock What do you think? I remember us discussing versioning the spec itself once it's stabilized and save the commit hash that's used to generated the client. Maybe we can just save the spec file itself in each repo for now till we have versioned spec?

**Comment by dblock** [comment]
> > wouldn't be better to commit the downloaded opensearch-openapi.yaml (or commit a 'frozen' link if possible ?) so it's clear which version has been used for the generation ?
> 
> That's a great idea. @dblock What do you think? I remember us discussing versioning the spec itself once it's stabilized and save the commit hash that's used to generated the client. Maybe we can just save the spec file itself in each repo for now till we have versioned spec?

we have releases of the spec, https://github.com/opensearch-project/opensearch-api-specification/releases, feel free to release 0.2.0

**Comment by xfournet** [comment]
In meantime i was able to retrieve the version used for the last generation (https://github.com/opensearch-project/opensearch-api-specification/actions/runs/12698838181)
The PR is up to date

File: api/_types/index.d.ts [hunk 1]
```diff
@@ -0,0 +1,233 @@
...
+import * as Transforms_Common from './transforms._common'
+import * as Wlm_Common from './wlm._common'
+import * as Global from './_global'
+
+export {
+  Common,
+  Common_Aggregations,
+  Common_Analysis,
+  Common_Mapping,
+  Common_QueryDsl,
```
[the remark this answers is not in the document]
Comment (nhtruong) [reply api/_types/index.d.ts:130]: That's what the API [index file](https://github.com/opensearch-project/opensearch-js/blob/main/api/index.d.ts) is doing. But I guess if the user doesn't know where the type is located, they can always use `NonNullable<API.UpdateByQuery_Request['body']>['query']`

**Review by nhtruong — APPROVED** [review]
