### ISSUE TITLE
[BUG] 3.9.0: `field` / `script` missing from `MetricAggregationBase` and `TermsAggregationFields` types (anyOf inside allOf dropped by generator?)

### ISSUE THREAD

**Issue by rktyt** [opensearch-project/opensearch-js#1154]
### What is the bug?
After upgrading from 3.6.0 to 3.9.0, TypeScript rejects `field` (and `script`) in metric aggregations (`cardinality`, `avg`, `sum`, `min`, `max`, …) and in `terms` aggregations.

In 3.9.0, `api/_types/_common.aggregations.d.ts` has:

```ts
export type MetricAggregationBase = {
  missing?: Common.FieldValue;
}

export type TermsAggregationFields = {
  collect_mode?: TermsAggregationCollectMode;
  exclude?: TermsExclude;
  execution_hint?: TermsAggregationExecutionHint;
  format?: string;
  include?: TermsInclude;
  min_doc_count?: number;
  missing?: Common.FieldValue;
  order?: AggregateOrder;
  shard_min_doc_count?: number;
  shard_size?: number;
  show_term_doc_count_error?: boolean;
  size?: number;
  value_type?: ValueType;
}
```

Neither type has `field` or `script`. In 3.6.0, `MetricAggregationBase` and `TermsAggregation` both had `field?: Common.Field` and `script?: Common.Script`.

Other aggregation types in 3.9.0 still have `field`, for example `RareTermsAggregationFields`, `HistogramAggregationFields` and `DateHistogramAggregationFields`.

In the API specification (`spec/schemas/_common.aggregations.yaml`), `MetricAggregationBase` defines `field` / `script` inside an `anyOf` nested in `allOf`:

```yaml
MetricAggregationBase:
  allOf:
    - type: object
      properties:
        missing:
          $ref: '_common.yaml#/components/schemas/FieldValue'
    - anyOf:
        - type: object
          properties:
            field:
              $ref: '_common.yaml#/components/schemas/Field'
        - type: object
          properties:
            script:
              $ref: '_common.yaml#/components/schemas/Script'
```

So the spec looks correct, and the API generator seems to drop the `anyOf` branch of `allOf`. `TermsAggregationFields` probably has the same cause. I only compared the generated output for it and have not checked its spec definition.

### How can one reproduce the bug?
1. Install `@opensearch-project/opensearch@3.9.0`.
2. Type-check the following:

```ts
import type { API } from '@opensearch-project/opensearch'

const body: API.Msearch_RequestBody = [
  {
    query: { match_all: {} },
    aggregations: {
      unique_user: {
        cardinality: { field: 'userId.keyword' },
      },
      top_products: {
        terms: { field: 'productCode.keyword', size: 100 },
      },
    },
    size: 0,
  },
]
```

3. `tsc --noEmit` reports:

```
error TS2353: Object literal may only specify known properties, and 'field' does not exist in type 'CardinalityAggregation'.
error TS2353: Object literal may only specify known properties, and 'field' does not exist in type 'TermsAggregationFields'.
```

The same code type-checks without errors on 3.6.0.

### What is the expected behavior?
`MetricAggregationBase` (and so `CardinalityAggregation`, `AvgAggregation`, etc.) and `TermsAggregationFields` should accept `field` and `script`, as the API specification defines and as 3.6.0 did. For example:

```ts
export type MetricAggregationBase = {
  missing?: Common.FieldValue;
} & ({ field?: Common.Field } | { script?: Common.Script })
```

(or with plain optional `field?` / `script?` properties, as in 3.6.0).

### What is your host/environment?
- `@opensearch-project/opensearch`: 3.9.0 (worked on 3.6.0)
- TypeScript: 6.0.3
- Node.js: v22.22.3
- OS: Linux (Docker, linuxkit kernel 7.0.12) on macOS host

### Do you have any screenshots?
N/A

### Do you have any additional context?
- 3.9.0 includes "Updated API specification from September 23, 2026" and several API generator changes (CHANGELOG), so the regression probably comes from one of those.
- Related earlier issue about missing aggregation properties in request body types: #956.
