### ISSUE TITLE
[BUG]  Cannot find module: Opensearch Error on node 18

### ISSUE THREAD

**Issue by PaaPaul** [opensearch-project/opensearch-js#663]
### What is the bug?
I got a module not found error when using the package in lambda after upgrading node from 16 to 18 

### How can one reproduce the bug?
 - Install package
 - Use lambda `Runtime: nodejs18.x`
 - Run Lambda function

### What is the expected behavior?
No errors or warning

### What is your host/environment?
 node v18

### Do you have any screenshots?
![Screenshot 2023-12-06 at 09 13 03](https://github.com/opensearch-project/opensearch-js/assets/109964202/9b4864cd-a527-4084-934a-e60620de25f2)

**Comment by dblock** [comment]
Want to try to add node 18 to CI?

**Comment by PaaPaul** [comment]
> @PaaPaul What does your `index.mjs` file look like?

@nhtruong, do not have any file in my repo named that. This only pops up when node is at 18.

**Comment by nhtruong** [comment]
We're already testing this against [NodeJS 18.x](https://github.com/opensearch-project/opensearch-js/blob/main/.github/workflows/integration.yml#L23). This is an issue in `index.mjs` in lambda.
